README.md

- Fixed version number in the title
- Added extra info about the great Raspbian (32bit kernel) vs. MongoDB (64bit kernel req.) debate
- Fixed some typos :)

Minor extra info & fixes

---

docker/monolithic-entrypoint.sh
monolithic.Dockerfile

will need the following build rules added to docker hub:

adds secondary Dockerfile for parallel monolithic image

---

package-lock.json
package.json

Add old babel eslint package 

---

package-lock.json
package.json

Reverts NotExpectedYet/OctoFarm#281

Revert "Add old babel eslint package "

---

CHANGELOG.md
client_src/js/lib/modules/printerSettings.js
config/db.js
server_src/runners/state.js

Fix wol settings

---

.github/workflows/docker_builds.yml
.github/workflows/docker_builds_alpine.yml
.github/workflows/docker_builds_monolithic.yml
Dockerfile
gulpfile.js
monolithic.Dockerfile
package-lock.json

Sadly flavoured version is not possible now.

Add docker build action to dev tag

---

views/system.ejs

Added new patreons on £10+ Tier

Updated Patreons on £10 Tier

---

app-test.js
app.js
package-lock.json
server_src/config/auth.js
server_src/routes/index.js
server_src/routes/serverChecks.js
server_src/runners/softwareUpdateChecker.js
server_src/utils/env.utils.js
test/api/mock-data/package.json
test/api/server-check.test.js
views/layout.ejs

Remove dirname usage

---

docker/alpine-entrypoint.sh
monolithic.Dockerfile

Just updated the alpine image for now.

Update alpine / monolithic branch to use npm ci

---

views/layout.ejs

Unrig the explosive skunk left behind by our creator

---

app-core.js
app-env.js
app-test.js
app.js
server_src/app.constants.js
server_src/lib/logger.js
server_src/routes/databaseIssue.js
server_src/routes/index.js
server_src/settings/serverSettings.js
server_src/utils/env.utils.js
test/api/settings-check.test.js
views/databaseIssue.ejs
views/system.ejs

isDocker safe fixes:
env utils:
constants:
fixed tests + bug:
Tested by clearing the .env keys and restart

Fix env, fix variables and safety checks for pm2/nodemon/docker modes

---

package-lock.json

npm update lock file

---

CHANGELOG.md

Added my noteworthy work to changelog

---

CHANGELOG.md
package.json

All compiled and updated changelog. Removed prelease from package.json

Update/version 1.1.13

---

views/system.ejs

removal of patreon

---

package-lock.json

Had prerelease version in there

Update lock file to have latest version

---

server_src/lib/serverCommands.js
server_src/utils/__mocks__/npm.utils.js
server_src/utils/git.utils.js
test/application/__mocks__/simple-git.js
test/application/server-commands.test.js

~I requested these on the last PR, but got skipped. Thought as updater is super important I'd add them myself.~
Fixes:

simple-git scenario tests

---

package-lock.json
package.json
server_src/lib/serverCommands.js
server_src/utils/system-paths.utils.js
test/application/server-commands.test.js

Fixed #501 - Added a check if command exists and timeout in restart command

---

CHANGELOG.md
server_src/lib/serverCommands.js
server_src/utils/__mocks__/npm.utils.js
server_src/utils/npm.utils.js
test/application/server-commands.test.js

Couldn't use those packages they both relied on importing npm, which is broken it seems due to a filter command. 
Made enhancements to the original to make it detect the missing packages and install individually.

npm utilities improvement

---

.gitignore
server_2x/src/api/legacy_lib/dataFunctions/historyClean.js
server_2x/src/printers/entities/mocks/printer-history-entity.mock.ts
server_2x/src/printers/interfaces/history-cache.interface.ts
server_2x/src/printers/models/apex-key-value.model.ts
server_2x/src/printers/models/history-cache-item.model.ts
server_2x/src/printers/models/history-file.model.ts
server_2x/src/printers/models/history-statistics.model.ts
server_2x/src/printers/models/job-analysis.model.ts
server_2x/src/printers/models/spool.model.ts
server_2x/src/printers/printers.constants.ts
server_2x/src/printers/printers.module.ts
server_2x/src/printers/services/history-cache.service.ts
server_2x/src/printers/services/history.cache.spec.ts
server_2x/src/printers/services/history.cache.ts
server_2x/src/printers/services/history.service.ts
server_2x/src/printers/services/mock-data/Histories.json
server_2x/src/printers/services/mock-data/HistoryStatisticsReference.json
server_2x/src/printers/services/mock-data/HistoryStatisticsReferenceUninitiated.json
server_2x/src/printers/utils/array.util.ts
server_2x/src/printers/utils/html.util.ts
server_2x/src/printers/utils/number.util.ts
server_2x/src/printers/utils/print-cost.util.ts
server_2x/src/printers/utils/property.util.ts
server_2x/src/printers/utils/time.util.ts
server_2x/src/settings/services/server-settings-cache.service.ts
server_2x/src/settings/settings.module.ts
server_2x/src/utils/types/fixed.type.ts
server_2x/tsconfig.json

Follows in footsteps of V1 history clean as close as possible

366 v2 history clean

---

CHANGELOG.md
server_src/lib/dataFunctions/printerClean.js

Two bugs solved apart from printer settings

---

CHANGELOG.md
app.js
package-lock.json
package.json
server_src/runners/filamentManagerPlugin.js
server_src/runners/history.js

Upgrade mongoose, fix circular import, fix ensureIndex warning

---

CHANGELOG.md
server_src/lib/dataFunctions/fileClean.js
server_src/lib/dataFunctions/settingsClean.js
server_src/lib/tests/file-clean.test.js

Closes #425 
Draft until #419 is merged.

FileClean refactor

---

CHANGELOG.md
app-core.js
server_src/lib/logger.js
server_src/runners/printerTicker.js
server_src/runners/state.js
server_src/services/octoprint/__mocks__/octoprint-api.service.js
server_src/services/octoprint/octoprint-api-client.service.js
server_src/services/octoprint/octoprint-api.service.js
test/application/octoprint/octoprint-api-client-service.test.js
test/application/state.test.js

574 state split

---

Dockerfile
alpine.Dockerfile
monolithic.Dockerfile
package-lock.json
package.json

Update to latest minor version of Node and Alpine

---

README.md

This makes it easier to forward users to FarmPi

📘 Add the FarmPi to readme

---

CHANGELOG.md
server_src/models/Filament.js
server_src/runners/filamentManagerPlugin.js
server_src/runners/history.runner.js
server_src/runners/state.js
server_src/services/octoprint/octoprint-api-client.service.js
server_src/services/octoprint/octoprint-service.constants.js
test/api/printers-settings.test.js
test/api/printers.test.js
test/api/server-update.test.js
test/api/sse-dashboard.test.js
test/api/sse-printers-info.test.js
test/application/runners/history-runner.test.js
test/application/system-info-runner.test.js

This depends on #646 cleanup
Why DI? Because it makes testing an absolute breeze. No it does not scale in the current way and it basically makes this code like a ticking time bomb for V2.

🧪 Chore/history refactor di injected

---

client_src/package-lock.json
client_src/package.json
package-lock.json
package.json

Hotfix problem for a user requiring dev container

Update client bundle and octofarm installation

---

package-lock.json
package.json

Removes hexnut as we dont want this on dev.

Remove hexnut as we are moving away from  it

---

client_src/js/lib/octoprint.js
package-lock.json
package.json
server_2x/views/layout.ejs

- Revert v2 layout view change
- add slight OP client change 
- add event emitter dep

🐦non-breaking administration and OP client change

---

client_src/js/lib/octofarm_client.js

@NotExpectedYet this was not throwing. Feel free to merge this or take over the branch for further client error handling

Missing UI import in client

---

server_src/runners/state.js

#731 - This was a mistake on my part from switching to the big one branch.

fix incorrect ws url fix (#731)

---

CHANGELOG.md
client_src/js/services/octofarm-client.service.js
client_src/package-lock.json
server_2x/views/system.ejs
server_src/routes/room-data.controller.js
server_src/tasks.js
views/partials/System/systemClient.ejs

🎮 refactor roomdata API

---

server_src/runners/state.js

Fixes the websocket close regressions

Changed: Fixed regression from yesterdays push

---

.github/workflows/development-release-publish.yml
CHANGELOG.md
client/js/constants/file-types.constants.js
client/js/file-manager.runner.js
client/js/pages/printer-manager/functions/bulk-commands-functions.js
client/js/services/printer-file-manager.service.js
client/package-lock.json
server/package-lock.json

Adds support for octoprint-bettergrblsupport and octoprint-chituboard plugins

feat: additional file types

---

server/services/printers/create-octoprint.service.js

There are issues with printer onboarding.

fix(server): fix printer onboarding 

---

.github/workflows/todo-analysis.yml
client/js/exceptions/octofarm-client.exceptions.js
client/js/system.runner.js
client/js/templates/camera.template.js
server/services/octoprint.service.js
server/services/octoprint/octoprint-api-client.service.js
server/services/octoprint/octoprint-websocket-client.service.js
server/services/octoprint/octoprint-websocket-message.service.js
server/services/octoprint/utils/octoprint-event.utils.js
server/services/octoprint/utils/octoprint-plugin.utils.js
server/services/octoprint/utils/octoprint-websocket-helpers.utils.js
server/services/printer-manager.service.js
server/store/printers.store.js
server/utils/env.utils.js

Automatically creates issues based on TODO comments. 
Test to see if it's liked...

chore(main): auto issue generation based on todo comments

---

.github/workflows/docker_builds.yml
.github/workflows/docker_builds_monolithic.yml
client/css/octofarm.css
client/js/pages/printer-manager/templates/printer-table-row.templates.js
client/js/services/octofarm-client.service.js
client/js/services/octoprint/octoprint-client.service.js
client/js/services/printer-action-buttons.service.js
client/js/services/printer-logs.service.js
client/js/services/printer-power.service.js
client/js/services/printer-settings.service.js
client/js/utils/ui.js
docker/Dockerfile
docker/entrypoint.sh
docker/monolithic-entrypoint.sh
server/models/Printer.js
server/models/userActionsLog.js
server/routes/printer-manager.routes.js
server/services/active-user-log.service.js
server/services/error-capture.service.js
server/services/history-capture.service.js
server/services/octoprint/utils/octoprint-event.utils.js
server/services/octoprint/utils/octoprint-plugin.utils.js
server/services/printer-cleaner.service.js
server/services/printers/create-octoprint.service.js
server/store/printers.store.js
server/utils/mapping.utils.js
server/views/partials/PrinterManager/octoPrintActionBtns.ejs
server/views/partials/PrinterManager/printerLogs.modal.ejs
server/views/partials/PrinterManager/printerManagementBtns.ejs

chore(main): history and various

---

client/js/pages/monitoring/monitoring.updater.js
client/js/pages/monitoring/services/printer-current-job.service.js
client/js/pages/printer-manager/functions/printer-manager.functions.js
client/js/pages/printer-manager/printer-data.js
client/js/pages/printer-manager/services/printer-statistics.service.js
client/js/pages/printer-manager/templates/printer-table-row.templates.js
client/js/services/octofarm-client.service.js
client/js/services/printer-action-buttons.service.js
client/js/utils/octofarm.utils.js
server/routes/printer-manager.routes.js
server/services/octoprint/octoprint-api-client.service.js
server/services/octoprint/octoprint-api.service.js
server/services/octoprint/octoprint-websocket-client.service.js
server/services/octoprint/octoprint-websocket-message.service.js
server/services/octoprint/utils/octoprint-event.utils.js
server/services/octoprint/utils/octoprint-plugin.utils.js
server/services/printer-manager.service.js
server/services/printers/create-octoprint.service.js
server/store/printers.store.js

Fix missed printer manager stuff from yesterday 
improve logging of plugin data

chore(main): fix missed printer manager stuff

---

client/js/services/file-manager.service.js
server/store/printers.store.js

- [ x ] File manager thinks printers are offline due to missing fullyScanned key
- [ x ] File manager tries to sort a folder with missing id flag

chore(main): fix two file manager regressiosn

---

client/js/history.runner.js
client/js/pages/file-manager/file-information-update.helpers.js
client/js/pages/file-manager/file.template.js
server/services/history-capture.service.js
server/services/server-commands.service.js
server/services/server-scripts.service.js
server/store/printers.store.js
server/utils/download.util.js

Adds bailout to timelapses and improves rendered files matching to only grab the one closest to OctoFarms endDate registered in history. 
Fixes pm2 restart command
Fixes scripts not firing or testable

chore(main): timelapse improvements

---

CHANGELOG.md
client/js/pages/printer-manager/services/printer-settings.service.js
server/store/printers.store.js

Also removed the option to input it as it's use has been removed from the system

fix(main): fixed #995 Saving printer settings without toggle command caused json errors

---

server/store/printers.store.js

Co-authored-by: James <james@vexica.com>

refactor(server): remove uneeded console logging (#1281)
